### ISSUE TITLE
Error: deploy parameter failure: account authorization invalid at prestate_hash: XXXXXXXXXXXXXX

### ISSUE THREAD

**Issue by piotrwitek** [torusresearch/casper-embed#14]
Hey,

I have an issue when signing native transfer with the widget.

It usually works just after a fresh login with the widget.

When refreshing the browser and initializing the widget which takes state from the browser storage it is logged in automatically but when trying to sign a deploy it’s throwing an error in the console signifying the account is not authorized:

```
Error: deploy parameter failure: account authorization invalid at prestate_hash: 949141432941962e2c5ededaa9e19f331ac5b58aaba852218177c53ef9c7d6bc
```

**Comment by chaitanyapotti** [comment]
This is fixed now
